server:
  port: 50051
database:
  username: token
  path: ./secure-connect.zip #TODO-change this to correct path when deployed to fargate
  timeout: 30
pulsar:
  uri: pulsar+ssl://pulsar-gcp-europewest1.streaming.datastax.com:6651
  topic_name: persistent://witty-tenant/default/products
  token: some_token  